require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecialDatesController do

  # This should return the minimal set of attributes required to create a valid
  # SpecialDate. As you add validations to SpecialDate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2014-03-26" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpecialDatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all special_dates as @special_dates" do
      special_date = SpecialDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:special_dates).should eq([special_date])
    end
  end

  describe "GET show" do
    it "assigns the requested special_date as @special_date" do
      special_date = SpecialDate.create! valid_attributes
      get :show, {:id => special_date.to_param}, valid_session
      assigns(:special_date).should eq(special_date)
    end
  end

  describe "GET new" do
    it "assigns a new special_date as @special_date" do
      get :new, {}, valid_session
      assigns(:special_date).should be_a_new(SpecialDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested special_date as @special_date" do
      special_date = SpecialDate.create! valid_attributes
      get :edit, {:id => special_date.to_param}, valid_session
      assigns(:special_date).should eq(special_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpecialDate" do
        expect {
          post :create, {:special_date => valid_attributes}, valid_session
        }.to change(SpecialDate, :count).by(1)
      end

      it "assigns a newly created special_date as @special_date" do
        post :create, {:special_date => valid_attributes}, valid_session
        assigns(:special_date).should be_a(SpecialDate)
        assigns(:special_date).should be_persisted
      end

      it "redirects to the created special_date" do
        post :create, {:special_date => valid_attributes}, valid_session
        response.should redirect_to(SpecialDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved special_date as @special_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialDate.any_instance.stub(:save).and_return(false)
        post :create, {:special_date => { "date" => "invalid value" }}, valid_session
        assigns(:special_date).should be_a_new(SpecialDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialDate.any_instance.stub(:save).and_return(false)
        post :create, {:special_date => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested special_date" do
        special_date = SpecialDate.create! valid_attributes
        # Assuming there are no other special_dates in the database, this
        # specifies that the SpecialDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpecialDate.any_instance.should_receive(:update).with({ "date" => "2014-03-26" })
        put :update, {:id => special_date.to_param, :special_date => { "date" => "2014-03-26" }}, valid_session
      end

      it "assigns the requested special_date as @special_date" do
        special_date = SpecialDate.create! valid_attributes
        put :update, {:id => special_date.to_param, :special_date => valid_attributes}, valid_session
        assigns(:special_date).should eq(special_date)
      end

      it "redirects to the special_date" do
        special_date = SpecialDate.create! valid_attributes
        put :update, {:id => special_date.to_param, :special_date => valid_attributes}, valid_session
        response.should redirect_to(special_date)
      end
    end

    describe "with invalid params" do
      it "assigns the special_date as @special_date" do
        special_date = SpecialDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_date.to_param, :special_date => { "date" => "invalid value" }}, valid_session
        assigns(:special_date).should eq(special_date)
      end

      it "re-renders the 'edit' template" do
        special_date = SpecialDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_date.to_param, :special_date => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested special_date" do
      special_date = SpecialDate.create! valid_attributes
      expect {
        delete :destroy, {:id => special_date.to_param}, valid_session
      }.to change(SpecialDate, :count).by(-1)
    end

    it "redirects to the special_dates list" do
      special_date = SpecialDate.create! valid_attributes
      delete :destroy, {:id => special_date.to_param}, valid_session
      response.should redirect_to(special_dates_url)
    end
  end

end
