require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TraficosController do

  # This should return the minimal set of attributes required to create a valid
  # Trafico. As you add validations to Trafico, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date" => "2014-04-02" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TraficosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all traficos as @traficos" do
      trafico = Trafico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:traficos).should eq([trafico])
    end
  end

  describe "GET show" do
    it "assigns the requested trafico as @trafico" do
      trafico = Trafico.create! valid_attributes
      get :show, {:id => trafico.to_param}, valid_session
      assigns(:trafico).should eq(trafico)
    end
  end

  describe "GET new" do
    it "assigns a new trafico as @trafico" do
      get :new, {}, valid_session
      assigns(:trafico).should be_a_new(Trafico)
    end
  end

  describe "GET edit" do
    it "assigns the requested trafico as @trafico" do
      trafico = Trafico.create! valid_attributes
      get :edit, {:id => trafico.to_param}, valid_session
      assigns(:trafico).should eq(trafico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trafico" do
        expect {
          post :create, {:trafico => valid_attributes}, valid_session
        }.to change(Trafico, :count).by(1)
      end

      it "assigns a newly created trafico as @trafico" do
        post :create, {:trafico => valid_attributes}, valid_session
        assigns(:trafico).should be_a(Trafico)
        assigns(:trafico).should be_persisted
      end

      it "redirects to the created trafico" do
        post :create, {:trafico => valid_attributes}, valid_session
        response.should redirect_to(Trafico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trafico as @trafico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trafico.any_instance.stub(:save).and_return(false)
        post :create, {:trafico => { "date" => "invalid value" }}, valid_session
        assigns(:trafico).should be_a_new(Trafico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trafico.any_instance.stub(:save).and_return(false)
        post :create, {:trafico => { "date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trafico" do
        trafico = Trafico.create! valid_attributes
        # Assuming there are no other traficos in the database, this
        # specifies that the Trafico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trafico.any_instance.should_receive(:update).with({ "date" => "2014-04-02" })
        put :update, {:id => trafico.to_param, :trafico => { "date" => "2014-04-02" }}, valid_session
      end

      it "assigns the requested trafico as @trafico" do
        trafico = Trafico.create! valid_attributes
        put :update, {:id => trafico.to_param, :trafico => valid_attributes}, valid_session
        assigns(:trafico).should eq(trafico)
      end

      it "redirects to the trafico" do
        trafico = Trafico.create! valid_attributes
        put :update, {:id => trafico.to_param, :trafico => valid_attributes}, valid_session
        response.should redirect_to(trafico)
      end
    end

    describe "with invalid params" do
      it "assigns the trafico as @trafico" do
        trafico = Trafico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trafico.any_instance.stub(:save).and_return(false)
        put :update, {:id => trafico.to_param, :trafico => { "date" => "invalid value" }}, valid_session
        assigns(:trafico).should eq(trafico)
      end

      it "re-renders the 'edit' template" do
        trafico = Trafico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trafico.any_instance.stub(:save).and_return(false)
        put :update, {:id => trafico.to_param, :trafico => { "date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trafico" do
      trafico = Trafico.create! valid_attributes
      expect {
        delete :destroy, {:id => trafico.to_param}, valid_session
      }.to change(Trafico, :count).by(-1)
    end

    it "redirects to the traficos list" do
      trafico = Trafico.create! valid_attributes
      delete :destroy, {:id => trafico.to_param}, valid_session
      response.should redirect_to(traficos_url)
    end
  end

end
